microservice:
  drive-service:
    endpoints:
      endpoint:
        uri: http://DRIVE-SERVICE/api/v1/uploadform/drive
  batch-service:
    endpoints:
      endpoint:
        uri: http://BATCH-SERVICE/api/v1/academy/batch
